CREATE TABLE IF NOT EXISTS "HealthStepSnapshot" (
"raceEntryId" TEXT PRIMARY KEY REFERENCES "RaceEntry"("id") ON DELETE CASCADE,
"steps" INTEGER NOT NULL CHECK ("steps" >= 0),
"windowStart" TIMESTAMP(3) NOT NULL,
"windowEnd" TIMESTAMP(3) NOT NULL,
"observedAt" TIMESTAMP(3) NOT NULL,
"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
