import Ionicons from '@expo/vector-icons/Ionicons';
import React,{useCallback,useRef,useState} from 'react';
import {View,Text,Pressable,Image,StyleSheet,ActivityIndicator} from 'react-native';
import {useFocusEffect,useNavigation} from '@react-navigation/native';
import {getProfileGallery,type ProfileGalleryData} from '../api/socialClient';
import {colors,fonts} from '../theme/tokens';
export function ProfileGallery({playerId}:{playerId:string}) {
 const navigation=useNavigation<any>();const [data,setData]=useState<ProfileGalleryData|null>(null);const [tab,setTab]=useState<'posts'|'games'>('posts');const [error,setError]=useState('');
 const generation=useRef(0);
 React.useEffect(()=>{setData(null);setError('');},[playerId]);
 const load=useCallback(()=>{const current=++generation.current;void getProfileGallery(playerId,{onCached:value=>{if(current===generation.current)setData(value);}}).then(value=>{if(current===generation.current){setData(value);setError('');}}).catch(()=>{if(current===generation.current)setError('Could not load this gallery. Tap to retry.');});},[playerId]);
 useFocusEffect(useCallback(()=>{load();return()=>{generation.current++;};},[load]));
 return <View style={styles.section}>
 <View style={styles.tabs}>{(['posts','games'] as const).map(key=><Pressable accessibilityRole="tab" accessibilityState={{selected:tab===key}} accessibilityLabel={key==='posts'?'Posts':'Games'} key={key} onPress={()=>setTab(key)} style={[styles.tab,tab===key&&styles.active]}><Ionicons name={key==='posts'?'grid-outline':'trophy-outline'} size={19} color={tab===key?colors.text:colors.sub}/><Text style={styles.heading}>{key==='posts'?'Posts':'Games'}{data?` (${data[key].length})`:''}</Text></Pressable>)}</View>
 {error?<Pressable onPress={load}><Text style={styles.body}>{error}</Text></Pressable>:null}
 {!data&&!error?<ActivityIndicator color={colors.accent}/>:null}
 <View style={styles.grid}>
 {tab==='posts'?data?.posts.map(post=><Pressable accessibilityRole="button" accessibilityLabel={`Open post: ${post.body.slice(0,50)}`} key={post.id} style={styles.tile} onPress={()=>navigation.navigate('Social',{screen:'SocialPost',params:{postId:post.id}})}>{post.imageUrl?<Image source={{uri:post.imageUrl}} style={StyleSheet.absoluteFillObject} resizeMode="cover"/>:<Text numberOfLines={4} style={styles.caption}>{post.body}</Text>}</Pressable>):data?.games.map(game=><Pressable accessibilityRole="button" accessibilityLabel={`Open game: ${game.name}`} key={game.id} style={styles.gameCard} onPress={()=>navigation.navigate('Play',{screen:'EventDetail',params:{eventId:game.id}})}><View style={styles.gameTop}><Ionicons name={game.sportKey==='tennis'||game.sportKey==='padel'?'tennisball-outline':game.sportKey==='football'?'football-outline':game.sportKey==='basketball'?'basketball-outline':game.sportKey.includes('rugby')?'american-football-outline':'fitness-outline'} size={24} color={colors.text}/><Text style={styles.caption}>{game.sportName}</Text></View><Text numberOfLines={2} style={styles.gameName}>{game.name}</Text><View style={styles.gameTop}><Ionicons name="trophy" size={16} color="#FFD166"/><Text style={styles.outcome}>{game.outcome}</Text></View><Text numberOfLines={3} style={styles.caption}>{game.summary}</Text><Text style={styles.date}>{new Date(game.finishedAt).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}{game.elapsedMs>0?` · ${Math.max(1,Math.round(game.elapsedMs/60000))} min`:''}</Text></Pressable>)}
 </View>
 {data&&!data[tab].length?<Text style={styles.body}>{tab==='posts'?'Your posts will appear here.':'Completed games appear here automatically.'}</Text>:null}
 </View>;
}
const styles=StyleSheet.create({section:{marginTop:8,marginBottom:16},tabs:{flexDirection:'row',marginBottom:8},tab:{flex:1,minHeight:48,flexDirection:'row',justifyContent:'center',gap:8,paddingVertical:12,alignItems:'center',borderBottomWidth:2,borderBottomColor:colors.line},active:{borderBottomColor:colors.accent},heading:{fontFamily:fonts.display,fontSize:16,color:colors.text},grid:{flexDirection:'row',flexWrap:'wrap',gap:3},tile:{width:'32.7%',aspectRatio:1,backgroundColor:colors.surfaceRaised,overflow:'hidden',padding:8,justifyContent:'center'},caption:{fontFamily:fonts.body,fontSize:11,lineHeight:15,color:colors.text},gameCard:{width:"49%",backgroundColor:colors.surfaceRaised,borderRadius:14,padding:12,gap:8,marginBottom:5},gameTop:{flexDirection:"row",alignItems:"center",gap:7},outcome:{flex:1,fontFamily:fonts.bodySemiBold,fontSize:12,color:colors.text},date:{fontFamily:fonts.body,fontSize:11,color:colors.sub},gameName:{fontFamily:fonts.display,fontSize:15,color:colors.text,marginBottom:5},body:{fontFamily:fonts.body,fontSize:13,color:colors.sub,marginVertical:12}});
