import {it,expect,vi,beforeEach} from 'vitest';
const tx=vi.hoisted(()=>({$queryRaw:vi.fn(),user:{findUniqueOrThrow:vi.fn(),delete:vi.fn()},raceEntry:{count:vi.fn(),deleteMany:vi.fn()},challenge:{count:vi.fn(),updateMany:vi.fn()},withdrawal:{count:vi.fn()},depositIntent:{count:vi.fn()},report:{deleteMany:vi.fn()},raceSquad:{findMany:vi.fn()},challengeInvite:{deleteMany:vi.fn()},challengeParticipant:{deleteMany:vi.fn()},appNotification:{deleteMany:vi.fn()},$executeRaw:vi.fn()}));
vi.mock('../src/lib/prisma.js',()=>({prisma:{$transaction:(fn:any)=>fn(tx)}}));
import {deleteAccount} from '../src/modules/account/deletion.js';
beforeEach(()=>{vi.clearAllMocks();tx.user.findUniqueOrThrow.mockResolvedValue({id:'u',email:'u@example.test',authVersion:2,walletBalanceCents:0});for(const entity of [tx.raceEntry,tx.challenge,tx.withdrawal,tx.depositIntent])entity.count.mockResolvedValue(0);tx.raceSquad.findMany.mockResolvedValue([]);});
it('never discards a wallet balance',async()=>{tx.user.findUniqueOrThrow.mockResolvedValue({authVersion:2,walletBalanceCents:100});await expect(deleteAccount('u',2)).rejects.toThrow('Withdraw');expect(tx.user.delete).not.toHaveBeenCalled();});
it('refuses stale authorization and pending financial obligations',async()=>{await expect(deleteAccount('u',1)).rejects.toThrow('security changed');tx.withdrawal.count.mockResolvedValue(1);await expect(deleteAccount('u',2)).rejects.toThrow('payment');expect(tx.user.delete).not.toHaveBeenCalled();});
it('does not revoke a provider before checking an active race',async()=>{tx.raceEntry.count.mockResolvedValue(1);const revoke=vi.fn();await expect(deleteAccount('u',2,revoke)).rejects.toThrow('competitions');expect(revoke).not.toHaveBeenCalled();});
it('removes restricted relationships and account after provider revocation',async()=>{const revoke=vi.fn();expect(await deleteAccount('u',2,revoke)).toEqual({deleted:true});expect(revoke).toHaveBeenCalledOnce();expect(tx.raceEntry.deleteMany).toHaveBeenCalledWith({where:{userId:'u'}});expect(tx.user.delete).toHaveBeenCalledWith({where:{id:'u'}});});
