import React,{useCallback,useEffect,useRef,useState} from 'react';
import {View,Text,ScrollView,Pressable,RefreshControl,StyleSheet,ActivityIndicator,AppState} from 'react-native';
import {useFocusEffect,useNavigation} from '@react-navigation/native';
import Ionicons from '@expo/vector-icons/Ionicons';
import {request} from '../../api/http';
import {getMyRaces} from '../../api/raceClient';
import type {RaceHistoryEntry} from '../../api/raceTypes';
import {AppleHealth,hasAppleHealth,type HealthStatus} from '../../lib/appleHealth';
import {ActivityIcon,ProgressBar,money} from '../pools/PoolVisuals';
import {activeRaces,activePools,competingMetrics} from './dashboard';
import {colors,fonts} from '../../theme/tokens';
import {PageMotion} from '../../components/PageMotion';
type Pool={id:string;title:string;currency:string;joined:boolean;status:string;durationDays:number;day:number;buyIn:number;capacity:number;players:Array<{isYou:boolean;status:string}>;goals:Array<{metric:string;target:number}>};
const labels:Record<string,string>={steps:'Steps',running:'Running',cycling:'Cycling',swimming:'Swimming',sleep:'Sleep',walkingDistance:'Recorded walks'};
const units:Record<string,string>={steps:'steps',running:'km',cycling:'km',swimming:'km',sleep:'hours',walkingDistance:'km'};
export function HomeScreen(){
 const nav=useNavigation<any>();const [races,setRaces]=useState<RaceHistoryEntry[]>([]);const [pools,setPools]=useState<Pool[]>([]);const [values,setValues]=useState<Record<string,number>>({});const [health,setHealth]=useState<HealthStatus>();const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);const [error,setError]=useState('');const metrics=competingMetrics(races,pools);const metricsKey=metrics.join(',');const live=useRef(true);const loading=useRef(false);
 useEffect(()=>()=>{live.current=false;},[]);
 const load=useCallback(async()=>{if(loading.current)return;loading.current=true;setBusy(true);const results=await Promise.allSettled([getMyRaces(),request<{pools:Pool[]}>('/pools',{cacheMode:'reload'})]);if(live.current){if(results[0].status==='fulfilled')setRaces(activeRaces(results[0].value.entries));if(results[1].status==='fulfilled')setPools(activePools(results[1].value.pools));setError(results.some(r=>r.status==='rejected')?'Some challenges could not refresh. Pull down to try again.':'');setLoaded(true);setBusy(false);}loading.current=false;},[]);
 useFocusEffect(useCallback(()=>{live.current=true;void load();const timer=setInterval(()=>{if(AppState.currentState==='active')void load();},60000);return()=>clearInterval(timer);},[load]));
 const readToday=useCallback(async()=>{if(!hasAppleHealth())return;try{const status=await AppleHealth.status();if(live.current)setHealth(status);if(!status.enabled)return;const today=await AppleHealth.dailyActivity({metrics:metricsKey?metricsKey.split(','):[]});if(live.current)setValues(today.values);}catch(e:any){if(live.current)setError(e.message??'Activity is unavailable.');}},[metricsKey]);
 useFocusEffect(useCallback(()=>{void readToday();if(hasAppleHealth())void AppleHealth.refresh().catch(()=>{});const timer=setInterval(()=>{if(AppState.currentState==='active')void readToday();},60000);return()=>clearInterval(timer);},[readToday]));
 useEffect(()=>{if(!hasAppleHealth())return;let ended=false;let remove:(()=>Promise<void>)|undefined;void AppleHealth.addListener('changed',s=>{if(!s.syncing)void readToday();}).then(h=>{if(ended)void h.remove();else remove=()=>h.remove();});return()=>{ended=true;void remove?.();};},[readToday]);
 const stats=metrics;
 return <PageMotion><ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={busy&&loaded} onRefresh={()=>{void load();void readToday();}} tintColor={colors.text}/>}><View style={s.row}><View style={{flex:1}}><Text style={s.title}>Home</Text><Text style={s.sub}>{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Find a challenge" onPress={()=>nav.navigate('Play',{screen:'PlayHome'})} style={s.explore}><Ionicons name="add" size={23} color={colors.text}/></Pressable></View>
 {error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}
 {!loaded?<ActivityIndicator color={colors.accent}/>:null}
 {stats.length>0?<><Text style={s.heading}>Today, for your challenges</Text><View style={s.grid}>{stats.map(m=><View key={m} style={s.stat}><ActivityIcon metric={m==='walkingDistance'?'steps':m}/><Text style={s.value}>{values[m]==null?'—':values[m].toLocaleString(undefined,{maximumFractionDigits:m==='steps'?0:2})}</Text><Text style={s.label}>{labels[m]}</Text><Text style={s.sub}>{m==='steps'&&values.walkingDistance!=null?`${values.walkingDistance.toLocaleString(undefined,{maximumFractionDigits:2})} km recorded walks`:units[m]}</Text></View>)}</View><Text style={s.small}>Today’s steps and recorded workouts, matched to your challenges.</Text>{hasAppleHealth()&&!health?.activityEnabled?<Pressable style={s.button} onPress={()=>{void AppleHealth.connect().then(()=>readToday()).catch(e=>setError(e.message));}}><Text style={s.label}>Set up Apple Health once</Text></Pressable>:<Text style={s.small}>{hasAppleHealth()?'Apple Health syncs automatically. Missing readings appear as —.':'Open ASTA on your iPhone to see today’s Apple Health activity.'}</Text>}</>:null}
 <View style={s.row}><Text style={[s.heading,{flex:1}]}>Your current challenges</Text><Text style={s.sub}>{races.length+pools.length}</Text></View>
 {loaded&&races.length+pools.length===0?<View style={s.empty}><Ionicons name="flag-outline" size={39} color={colors.text}/><Text style={s.heading}>Your next start is waiting</Text><Text style={s.sub}>Join a Pool or competition in Play. Your races and relevant daily activity will appear here.</Text><Pressable style={s.button} onPress={()=>nav.navigate('Play',{screen:'PlayHome'})}><Text style={s.label}>Explore Play</Text></Pressable></View>:null}
 {races.map(e=><Pressable key={e.id} accessibilityRole="button" onPress={()=>nav.navigate('RaceDetail',{raceId:e.raceId})} style={s.card}><View style={s.row}><ActivityIcon metric={e.race.metricKey}/><View style={{flex:1,gap:4}}><Text style={s.heading}>{e.race.name}</Text><Text style={s.sub}>Competition · {e.race.durationDays} days</Text></View><Ionicons name="chevron-forward" size={20} color={colors.sub}/></View><View style={s.row}><Text style={[s.label,{flex:1}]}>{e.race.status==='FILLING'?'Waiting for racers':e.race.status==='LOCKED'?'Starts soon':e.race.status==='RESOLVING'?'Confirming results':'In progress'}</Text><Text style={s.sub}>{money(e.entryFeeCents)} entry</Text></View>{e.race.endsAt?<Text style={s.small}>Ends {new Date(e.race.endsAt).toLocaleDateString()}</Text>:null}</Pressable>)}
 {pools.map(p=><Pressable key={p.id} accessibilityRole="button" onPress={()=>nav.navigate('PoolDetail',{id:p.id})} style={s.card}><View style={s.row}><ActivityIcon metric={p.goals[0].metric}/><View style={{flex:1,gap:4}}><Text style={s.heading}>{p.title}</Text><Text style={s.sub}>Pool · {p.status==='WAITING'?`${p.players.length}/${p.capacity} players`:p.status==='SCHEDULED'?'Starts soon':`Day ${p.day} of ${p.durationDays}`}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.sub}/></View>{p.goals.map(g=><Text style={s.label} key={g.metric}>{labels[g.metric]} · {g.target.toLocaleString()} {units[g.metric]} / day</Text>)}<ProgressBar value={p.status==='WAITING'?p.players.length/p.capacity:p.day/p.durationDays}/><Text style={s.sub}>{money(p.buyIn*p.players.length)} shared Pool</Text></Pressable>)}
 </ScrollView></PageMotion>;
}
const s=StyleSheet.create({page:{padding:18,gap:16,paddingBottom:40},title:{fontFamily:fonts.display,fontSize:30,color:colors.text},heading:{fontFamily:fonts.display,fontSize:18,color:colors.text},sub:{fontFamily:fonts.body,fontSize:13,color:colors.sub,lineHeight:20},small:{fontFamily:fonts.body,fontSize:12,color:colors.sub,lineHeight:18},label:{fontFamily:fonts.bodySemiBold,fontSize:14,color:colors.text},value:{fontFamily:fonts.display,fontSize:29,color:colors.text,marginTop:7},row:{flexDirection:'row',alignItems:'center',gap:12},explore:{padding:12,borderRadius:16,backgroundColor:colors.accent},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},stat:{flexGrow:1,flexBasis:'44%',backgroundColor:colors.surface,borderRadius:20,padding:18,gap:4},card:{padding:18,gap:14,backgroundColor:colors.surface,borderRadius:20},empty:{padding:24,gap:14,borderRadius:20,backgroundColor:colors.surface},button:{backgroundColor:colors.accent,borderRadius:14,padding:16,alignItems:'center'},error:{color:colors.fail,fontFamily:fonts.body,fontSize:13}});
