import React,{useEffect,useRef,useState} from 'react';
import {View,Text,ImageBackground,Animated,AccessibilityInfo,StyleSheet} from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import {LinearGradient} from 'expo-linear-gradient';
import {colors,fonts} from '../../theme/tokens';
export const poolIcons:Record<string,React.ComponentProps<typeof Ionicons>['name']>={steps:'footsteps',running:'walk',cycling:'bicycle',swimming:'water',sleep:'moon'};
export const money=(amount:number,currency?:string)=>currency==='ZAR'?`R ${(amount/100).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`:`${amount.toLocaleString()} credits`;
export function ActivityIcon({metric,size=23}:{metric:string;size?:number}){return <View style={v.icon}><Ionicons name={poolIcons[metric]??'fitness'} size={size} color={colors.text}/></View>;}
export function PoolHero(){return <ImageBackground source={require('../../../assets/pools/coastal-run.jpg')} style={v.hero} imageStyle={{borderRadius:22}}><LinearGradient colors={['transparent',colors.bg]} style={v.shade}><Text style={v.eyebrow}>A little every day.</Text><Text style={v.heroTitle}>{'Better habits.\nShared rewards.'}</Text><Text style={v.subtitle}>Meet your goals. Stay in together.</Text></LinearGradient></ImageBackground>;}
export function ProgressBar({value}:{value:number}){return <View style={v.track}><View style={[v.fill,{width:`${Math.max(0,Math.min(100,value*100))}%`}]}/></View>;}
const celebrated=new Set<string>();
export function WinCard({id,amount,currency,shared}:{id:string;amount:number;currency?:string;shared:boolean}){
 const animation=useRef(new Animated.Value(0)).current;const [show,setShow]=useState(false);
 useEffect(()=>{let live=true;let sequence:Animated.CompositeAnimation|undefined;void AccessibilityInfo.isReduceMotionEnabled().then(reduced=>{if(!live||reduced||celebrated.has(id))return;celebrated.add(id);setShow(true);sequence=Animated.timing(animation,{toValue:1,duration:1800,useNativeDriver:true});sequence.start(()=>{if(live)setShow(false);});});return()=>{live=false;sequence?.stop();};},[id,animation]);
 return <View accessibilityRole="summary" style={v.win}>{show?<View pointerEvents="none" style={StyleSheet.absoluteFill}>{Array.from({length:18},(_,i)=><Animated.View key={i} style={{position:'absolute',left:`${(i*17)%95}%`,top:0,width:6,height:10,borderRadius:2,backgroundColor:i%3===0?colors.text:i%3===1?colors.risk:colors.accent,opacity:animation.interpolate({inputRange:[0,.8,1],outputRange:[1,1,0]}),transform:[{translateY:animation.interpolate({inputRange:[0,1],outputRange:[-10,220+(i%3)*20]})},{rotate:animation.interpolate({inputRange:[0,1],outputRange:['0deg',`${180+i*40}deg`]})}]}}/>)}</View>:null}<Ionicons name="trophy" size={44} color={colors.risk}/><Text style={v.won}>You did it!</Text><Text style={v.amount}>{money(amount,currency)}</Text><Text style={v.caption}>{shared?'Your share of the Pool':'Last one standing. The Pool is yours.'}</Text><Text style={v.caption}>{currency==='ZAR'?'Added to your ASTA wallet':'Added to your test balance'}</Text></View>;
}
const v=StyleSheet.create({hero:{height:245,marginBottom:4,overflow:'hidden',borderRadius:22},shade:{flex:1,justifyContent:'flex-end',padding:20},eyebrow:{fontFamily:fonts.bodySemiBold,color:colors.text,fontSize:12,marginBottom:5},heroTitle:{fontFamily:fonts.display,fontSize:30,lineHeight:35,color:colors.text},subtitle:{fontFamily:fonts.body,color:colors.sub,fontSize:14,marginTop:7},icon:{width:44,height:44,borderRadius:14,backgroundColor:colors.accent,justifyContent:'center',alignItems:'center'},track:{height:6,borderRadius:3,backgroundColor:colors.line,overflow:'hidden'},fill:{height:6,backgroundColor:colors.sage,borderRadius:3},win:{padding:24,borderRadius:22,backgroundColor:colors.surfaceRaised,alignItems:'center',gap:10,overflow:'hidden',borderWidth:1,borderColor:colors.risk},won:{fontFamily:fonts.display,fontSize:25,color:colors.text},amount:{fontFamily:fonts.display,fontSize:36,color:colors.risk},caption:{fontFamily:fonts.body,fontSize:14,color:colors.sub,textAlign:'center'}});
