import React,{useCallback,useRef,useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,ActivityIndicator} from 'react-native';
import {useFocusEffect,useNavigation,useRoute} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {request} from '../../api/http';
import {colors,fonts} from '../../theme/tokens';
import {PageMotion} from '../../components/PageMotion';
const Stack=createNativeStackNavigator();
type Metric='steps'|'running'|'cycling'|'swimming'|'sleep';
type Goal={metric:Metric;target:number;bedtime?:number;wakeTime?:number};
type Player={id:string;name:string;status:string;payout?:number;eliminatedDay?:number;days:Record<string,boolean>;reports:Record<string,{values:Partial<Record<Metric,number>>;sleepStart?:string;sleepEnd?:string}>};
type Pool={id:string;title:string;status:string;durationDays:number;capacity:number;buyIn:number;timezone:string;startAt:string|null;goals:Goal[];players:Player[];isHost:boolean;joined:boolean;day:number;version:number;serverTime:string};
const labels:Record<Metric,string>={steps:'Walking',running:'Running',cycling:'Cycling',swimming:'Swimming',sleep:'Sleep'};
const units:Record<Metric,string>={steps:'steps',running:'km',cycling:'km',swimming:'km',sleep:'hours'};
const defaults:Record<Metric,string>={steps:'10000',running:'5',cycling:'20',swimming:'1',sleep:'8'};
function Button({title,onPress,disabled=false,secondary=false}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,(pressed||disabled)&&{opacity:.55}]}><Text style={[s.buttonText,secondary&&{color:colors.text}]}>{title}</Text></Pressable>;}
function Field({label,value,onChange,keyboard='default'}:{label:string;value:string;onChange:(v:string)=>void;keyboard?:'default'|'numeric'|'decimal-pad'}){return <View style={{gap:6}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} style={s.input} value={value} onChangeText={onChange} keyboardType={keyboard} autoCapitalize="none" autoCorrect={false}/></View>;}
function Shell({children}:{children:React.ReactNode}){return <PageMotion><ScrollView style={{flex:1,backgroundColor:colors.bg}} contentContainerStyle={s.content}><Text style={s.test}>POOLS · TEST CREDITS ONLY</Text>{children}</ScrollView></PageMotion>;}
const mutate=(id:string,action:string,body:unknown={})=>request<{pool:Pool}>(`/pools/${id}/${action}`,{method:'POST',body:JSON.stringify(body)});
export function PoolsScreen(){return <Stack.Navigator screenOptions={{headerShown:false,gestureEnabled:true}}><Stack.Screen name="PoolsHome" component={PoolList}/><Stack.Screen name="CreatePool" component={CreatePool}/><Stack.Screen name="PoolDetail" component={PoolDetail}/></Stack.Navigator>;}
function PoolList(){const navigation=useNavigation<any>();const [data,setData]=useState<{pools:Pool[];testBalance:number}|null>(null);const [error,setError]=useState('');
 const load=useCallback(()=>{request<{pools:Pool[];testBalance:number}>('/pools',{cacheMode:'reload'}).then(setData).catch(e=>setError(e.message));},[]);useFocusEffect(useCallback(()=>{load();},[load]));
 return <Shell><Text style={s.title}>Pools</Text><Text style={s.body}>Meet every daily goal. The last player standing wins immediately. Otherwise, finishers share the pool equally.</Text><Text style={s.note}>Prototype: activity is entered manually by the host for testing. No real money, deposits or withdrawals. Apple Health is not connected to Pools yet.</Text><Text style={s.label}>Your test balance: {data?.testBalance.toLocaleString()??'…'} credits</Text><Button title="Start a pool" onPress={()=>navigation.navigate('CreatePool')}/>{error?<><Text style={s.error}>{error}</Text><Button title="Retry" secondary onPress={load}/></>:null}{!data&&!error?<ActivityIndicator color={colors.accent}/>:null}{data?.pools.length===0?<Text style={s.note}>No pools yet. Start one and invite others, or fill it with test players.</Text>:null}{data?.pools.map(p=><Pressable accessibilityRole="button" key={p.id} style={s.card} onPress={()=>navigation.navigate('PoolDetail',{id:p.id})}><Text style={s.heading}>{p.title}</Text><Text style={s.body}>{p.goals.map(g=>labels[g.metric]).join(' + ')}</Text><Text style={s.note}>{p.durationDays} days · {p.players.length}/{p.capacity} players · {p.buyIn} credits each</Text><Text style={s.label}>{p.status.toLowerCase()} {p.joined?'· Joined':''} {p.isHost?'· Host':''}</Text></Pressable>)}</Shell>;
}
function time(value:string){if(!/^\d{2}:\d{2}$/.test(value))throw new Error('Use HH:MM for sleep times.');const [h,m]=value.split(':').map(Number);if(h>23||m>59)throw new Error('Use valid 24-hour times.');return h*60+m;}
function CreatePool(){const navigation=useNavigation<any>();const [requestId]=useState(()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16);return(c==='x'?r:(r&3)|8).toString(16);}));const [title,setTitle]=useState('');const [days,setDays]=useState('7');const [capacity,setCapacity]=useState('3');const [buyIn,setBuyIn]=useState('100');const [selected,setSelected]=useState<Metric[]>(['steps']);const [targets,setTargets]=useState(defaults);const [bed,setBed]=useState('23:00');const [wake,setWake]=useState('07:00');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
 const create=async()=>{setBusy(true);setError('');try{const goals=selected.map(metric=>({metric,target:Number(targets[metric]),...(metric==='sleep'?{bedtime:bed?time(bed):undefined,wakeTime:wake?time(wake):undefined}:{})}));const r=await request<{pool:Pool}>('/pools',{method:'POST',body:JSON.stringify({requestId,title,durationDays:Number(days),capacity:Number(capacity),buyIn:Number(buyIn),timezone,goals})});navigation.replace('PoolDetail',{id:r.pool.id});}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <Shell><Text style={s.title}>Start a pool</Text><Field label="Pool name" value={title} onChange={setTitle}/><View style={s.row}><View style={{flex:1}}><Field label="Days (7–365)" value={days} onChange={setDays} keyboard="numeric"/></View><View style={{flex:1}}><Field label="Players (2–50)" value={capacity} onChange={setCapacity} keyboard="numeric"/></View></View><Field label="Buy-in per person (test credits)" value={buyIn} onChange={setBuyIn} keyboard="numeric"/><Text style={s.heading}>Daily goals</Text><Text style={s.note}>Select one activity or combine several. Every selected goal must be completed each day.</Text><View style={s.chips}>{(Object.keys(labels) as Metric[]).map(m=><Pressable accessibilityRole="checkbox" accessibilityState={{checked:selected.includes(m)}} key={m} style={[s.chip,selected.includes(m)&&{backgroundColor:colors.accent}]} onPress={()=>setSelected(v=>v.includes(m)?v.filter(x=>x!==m):[...v,m])}><Text style={s.label}>{labels[m]}</Text></Pressable>)}</View>{selected.map(m=><Field key={m} label={`${labels[m]} per day (${units[m]})`} value={targets[m]} onChange={v=>setTargets(t=>({...t,[m]:v}))} keyboard="decimal-pad"/>)}{selected.includes('sleep')?<><Field label="Asleep by (HH:MM, optional)" value={bed} onChange={setBed}/><Field label="Awake by (HH:MM, optional)" value={wake} onChange={setWake}/><Text style={s.note}>Sleep is assigned to the day you wake up. Day 1 includes the preceding night. Only your main sleep counts. Hours, bedtime and wake deadline must all pass.</Text></>:null}<Text style={s.note}>You occupy the first place. The pool begins at midnight in {timezone} after all places fill. Missing a day eliminates you; credits stay in the pool. One remaining player wins all credits immediately. Otherwise, finishers split all credits. If nobody finishes, everyone is refunded. Leave before the start for a full refund.</Text>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}<Button disabled={busy||!selected.length} title={busy?'Creating…':'Create & join with test credits'} onPress={()=>void create()}/></Shell>;
}
type Draft={values:Partial<Record<Metric,string>>;sleepStart:string;sleepEnd:string};
function savedDraft(player:Player,day:number):Draft{const r=player.reports[String(day)];return {values:Object.fromEntries(Object.entries(r?.values??{}).map(([k,v])=>[k,String(v)])),sleepStart:r?.sleepStart??'',sleepEnd:r?.sleepEnd??''};}
function reportBody(pool:Pool,player:Player,draft:Draft){
 const values:Partial<Record<Metric,number>>={};
 for(const g of pool.goals.filter(g=>g.metric!=='sleep')){const text=draft.values[g.metric]?.trim();if(!text)throw new Error(`Enter ${labels[g.metric].toLowerCase()} for ${player.name}. Use 0 for a missed goal.`);const n=Number(text);if(!Number.isFinite(n)||n<0||(g.metric==='steps'&&!Number.isInteger(n)))throw new Error(`Check the total for ${player.name}.`);values[g.metric]=n;}
 if(pool.goals.some(g=>g.metric==='sleep')){if(!draft.sleepStart&&!draft.sleepEnd)return {participantId:player.id,day:pool.day,values};if(!draft.sleepStart||!draft.sleepEnd||!Number.isFinite(Date.parse(draft.sleepStart))||!Number.isFinite(Date.parse(draft.sleepEnd)))throw new Error(`Use complete sleep timestamps for ${player.name}.`);}
 return {participantId:player.id,day:pool.day,values,...(draft.sleepStart?{sleepStart:new Date(draft.sleepStart).toISOString()}:{}),...(draft.sleepEnd?{sleepEnd:new Date(draft.sleepEnd).toISOString()}:{})};
}
function PoolDetail(){
 const id=useRoute<any>().params.id;const [p,setPool]=useState<Pool|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const locked=useRef(false);const [confirmAdvance,setConfirmAdvance]=useState(false);const [drafts,setDrafts]=useState<Record<string,Draft>>({});
 const load=useCallback(()=>{request<{pool:Pool}>(`/pools/${id}`,{cacheMode:'reload'}).then(r=>{setPool(r.pool);setError('');}).catch(e=>setError(e.message));},[id]);useFocusEffect(useCallback(()=>{load();},[load]));
 const act=async(action:string,body:unknown={})=>{if(locked.current)return;locked.current=true;setBusy(true);setError('');try{const next=(await mutate(id,action,body)).pool;setPool(next);if(action==='test-advance')setDrafts({});setConfirmAdvance(false);}catch(e:any){setError(e.message);}finally{locked.current=false;setBusy(false);}};
 const draftFor=(player:Player)=>drafts[`${p!.day}:${player.id}`]??savedDraft(player,p!.day);
 const savePlayer=(player:Player)=>{try{void act('test-report',reportBody(p!,player,draftFor(player)));}catch(e:any){setError(e.message);}};
 const closeDay=()=>{try{const reports=p!.status==='ACTIVE'?p!.players.filter(x=>x.status==='ACTIVE').map(x=>reportBody(p!,x,draftFor(x))):undefined;void act('test-advance',{version:p!.version,reports});}catch(e:any){setError(e.message);setConfirmAdvance(false);}};
 if(!p)return <Shell><Text style={s.title}>Pool</Text>{error?<><Text style={s.error}>{error}</Text><Button title="Retry" onPress={load}/></>:<ActivityIndicator color={colors.accent}/>}</Shell>;
 return <Shell><Text style={s.title}>{p.title}</Text><Text style={s.heading}>{p.status==='WAITING'?'Waiting for players':p.status==='SCHEDULED'?'Ready to start':p.status==='COMPLETED'?'Pool finished':`Day ${p.day} of ${p.durationDays}`}</Text><Text style={s.body}>{p.players.length}/{p.capacity} players · {p.buyIn*p.players.length} test credits in the pool</Text><Text style={s.note}>Timezone: {p.timezone}{p.startAt?` · Starts ${new Date(p.startAt).toLocaleString(undefined,{timeZone:p.timezone})}`:''}</Text>{p.goals.map(g=><Text key={g.metric} style={s.label}>{labels[g.metric]}: {g.target} {units[g.metric]} daily{g.bedtime!==undefined?` · asleep by ${String(Math.floor(g.bedtime/60)).padStart(2,'0')}:${String(g.bedtime%60).padStart(2,'0')}`:''}{g.wakeTime!==undefined?` · awake by ${String(Math.floor(g.wakeTime/60)).padStart(2,'0')}:${String(g.wakeTime%60).padStart(2,'0')}`:''}</Text>)}{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{!p.joined&&p.status==='WAITING'?<Button disabled={busy} title={`Join · ${p.buyIn} test credits`} onPress={()=>void act('join')}/>:null}{p.joined&&['WAITING','SCHEDULED'].includes(p.status)?<Button disabled={busy} secondary title="Leave & refund test credits" onPress={()=>void act('leave')}/>:null}
 {p.isHost&&p.status!=='COMPLETED'?<View style={s.card}><Text style={s.heading}>Host test controls</Text><Text style={s.note}>Everyone at or above every daily target stays in. Higher totals do not knock anyone else out. Closing a test day saves all entered totals together before checking players. Enter 0 to test a missed goal.</Text>{p.status==='WAITING'?<Button disabled={busy} title="Fill remaining places with test players" onPress={()=>void act('test-fill')}/>:null}{['ACTIVE','SCHEDULED'].includes(p.status)?confirmAdvance?<><Text style={s.body}>Save all entered totals and close this day? Only players below a daily target will be eliminated.</Text>{p.players.filter(x=>x.status==='ACTIVE').map(x=><Text key={x.id} style={s.note}>{x.name}: {p.goals.map(g=>g.metric==='sleep'?`Sleep: ${draftFor(x).sleepStart||'no sleep recorded'}`:`${draftFor(x).values[g.metric]||'not entered'} ${units[g.metric]}`).join(' · ')}</Text>)}<Button disabled={busy} title="Save all totals & confirm next day" onPress={closeDay}/><Button secondary disabled={busy} title="Keep editing" onPress={()=>setConfirmAdvance(false)}/></>:<Button disabled={busy} title={p.status==='SCHEDULED'?'Jump to test day 1':'Save all totals & close day'} onPress={()=>p.status==='SCHEDULED'?closeDay():setConfirmAdvance(true)}/>:null}</View>:null}
 {p.status==='COMPLETED'?<Text style={s.body}>{p.players.some(x=>x.status==='FINISHED')?(p.players.filter(x=>x.status==='FINISHED').length===1?'The last player standing wins the entire pool.':'Finishers share the entire pool.'):'Nobody finished, so every entry has been refunded.'} All amounts are test credits.</Text>:null}
 <Text style={s.heading}>Players</Text>{p.players.map(player=><View key={player.id} style={s.card}><Text style={s.heading}>{player.name}</Text><Text style={s.note}>{player.status.toLowerCase()}{player.eliminatedDay?` · out on day ${player.eliminatedDay}`:''} · {Object.values(player.days).filter(Boolean).length} days passed</Text>{player.payout!==undefined?<Text style={s.label}>{player.payout} test credits returned</Text>:null}{p.isHost&&p.status==='ACTIVE'&&player.status==='ACTIVE'?<ReportForm pool={p} player={player} draft={draftFor(player)} onChange={d=>{setDrafts(v=>({...v,[`${p.day}:${player.id}`]:d}));setConfirmAdvance(false);}} busy={busy} save={()=>savePlayer(player)}/>:null}</View>)}<Button secondary disabled={busy} title="Refresh pool" onPress={load}/></Shell>;
}
function ReportForm({pool,player,draft,onChange,save,busy}:{pool:Pool;player:Player;draft:Draft;onChange:(d:Draft)=>void;save:()=>void;busy:boolean}){
 const report=player.reports[String(pool.day)];const unchanged=JSON.stringify(draft)===JSON.stringify(savedDraft(player,pool.day));
 return <View style={{gap:10}}><Text style={s.note}>Day {pool.day} test totals</Text>{pool.goals.filter(g=>g.metric!=='sleep').map(g=><Field key={g.metric} label={`${player.name} · ${labels[g.metric]} (${units[g.metric]})`} value={draft.values[g.metric]??''} onChange={v=>onChange({...draft,values:{...draft.values,[g.metric]:v}})} keyboard="decimal-pad"/>)}{pool.goals.some(g=>g.metric==='sleep')?<><Text style={s.note}>Test clock: {new Date(pool.serverTime).toLocaleString(undefined,{timeZone:pool.timezone})}. Enter the main sleep ending on this day. Leave both sleep fields empty to simulate no sleep.</Text><Field label={`${player.name} · Sleep began (date, time & timezone)`} value={draft.sleepStart} onChange={sleepStart=>onChange({...draft,sleepStart})}/><Field label={`${player.name} · Woke up (date, time & timezone)`} value={draft.sleepEnd} onChange={sleepEnd=>onChange({...draft,sleepEnd})}/></>:null}<Button disabled={busy} secondary title={report?'Update saved test totals':'Save test totals'} onPress={save}/><Text style={s.note}>{report&&unchanged?'Saved. This day is assessed when it closes.':'These entries will be saved when you close the test day, or tap Save test totals.'}</Text></View>;
}
const s=StyleSheet.create({content:{padding:16,paddingBottom:40,gap:14},title:{fontFamily:fonts.display,fontSize:27,color:colors.text},heading:{fontFamily:fonts.display,fontSize:18,color:colors.text},body:{fontFamily:fonts.body,fontSize:15,color:colors.text,lineHeight:22},note:{fontFamily:fonts.body,fontSize:13,color:colors.sub,lineHeight:19},label:{fontFamily:fonts.bodySemiBold,fontSize:14,color:colors.text},test:{fontFamily:fonts.bodyBold,fontSize:11,color:colors.risk},input:{fontFamily:fonts.body,fontSize:16,color:colors.text,minHeight:48,padding:12,borderWidth:1,borderColor:colors.line,borderRadius:10,backgroundColor:colors.surface},button:{minHeight:46,borderRadius:12,padding:12,alignItems:'center',justifyContent:'center',backgroundColor:colors.accent},secondary:{backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.line},buttonText:{fontFamily:fonts.bodySemiBold,color:colors.onAccent,fontSize:14},card:{backgroundColor:colors.surface,padding:16,borderRadius:14,gap:12},row:{flexDirection:'row',gap:12},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{backgroundColor:colors.surfaceRaised,padding:13,borderRadius:12},error:{fontFamily:fonts.body,color:colors.fail,fontSize:14}});
